# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformCloudCli < Formula
  desc "Interactive CLI for operating workspaces in Terraform Cloud"
  homepage "https://github.com/bendrucker/terraform-cloud-cli"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bendrucker/terraform-cloud-cli/releases/download/v0.1.2/terraform-cloud-cli_0.1.2_darwin_amd64.tar.gz"
    sha256 "5b99060acafb2a976fa4ab1080bdd38a99169530be374dd12eb95c6dff77fc9b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bendrucker/terraform-cloud-cli/releases/download/v0.1.2/terraform-cloud-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "2472bc06158c3a5c420906839d0d1911fd224868deff9d0270273b9cfcc05476"
    end
  end

  def install
    bin.install "terraform-cloud"
  end
end
